import * as THREE from "three";
import { createPlanet, projectPosition } from "./planet-factory.js";
import { createShip } from "./ship.js";

export class Universe {
  constructor(canvas, onFocus, onFirstMovement = () => {}) { this.canvas = canvas; this.onFocus = onFocus; this.onFirstMovement = onFirstMovement; this.hasMoved = false; this.lowPower = matchMedia("(max-width: 700px)").matches || navigator.hardwareConcurrency <= 4; this.renderer = new THREE.WebGLRenderer({ canvas, antialias: !this.lowPower, powerPreference: "high-performance" }); this.renderer.setPixelRatio(Math.min(devicePixelRatio, this.lowPower ? 1.35 : 2)); this.scene = new THREE.Scene(); this.scene.background = new THREE.Color("#05050a"); this.scene.fog = new THREE.FogExp2("#05050a", .0022); this.camera = new THREE.PerspectiveCamera(58, 1, .1, 1600); this.camera.position.set(0, 5.5, 18); this.clock = new THREE.Clock(); this.keys = new Set(); this.raycaster = new THREE.Raycaster(); this.pointer = new THREE.Vector2(); this.planets = []; this.running = false; this.ship = createShip(); this.scene.add(this.ship, new THREE.HemisphereLight("#b7b4ff", "#080814", 1.25)); const sun = new THREE.PointLight("#fff4e5", 1000, 700); sun.position.set(-90, 110, 50); this.scene.add(sun); this.addStars(); this.bind(); this.resize(); }
  addStars() { const count = this.lowPower ? 900 : 2600; const positions = new Float32Array(count * 3); for (let i = 0; i < count; i++) { const r = 190 + Math.random() * 600; const a = Math.random() * Math.PI * 2; positions[i * 3] = Math.cos(a) * r; positions[i * 3 + 1] = (Math.random() - .5) * r; positions[i * 3 + 2] = Math.sin(a) * r; } const geometry = new THREE.BufferGeometry(); geometry.setAttribute("position", new THREE.BufferAttribute(positions, 3)); this.scene.add(new THREE.Points(geometry, new THREE.PointsMaterial({ color: "#e7e9ff", size: this.lowPower ? 1 : 1.35, transparent: true, opacity: .8, sizeAttenuation: true }))); }
  setProjects(projects) { this.planets.forEach((planet) => this.scene.remove(planet)); this.planets = projects.map((project) => { const planet = createPlanet(project, this.lowPower ? 20 : 32); planet.position.copy(projectPosition(project)); this.scene.add(planet); return planet; }); }
  bind() { addEventListener("keydown", (event) => { if (["INPUT", "TEXTAREA"].includes(document.activeElement?.tagName)) return; this.keys.add(event.code); if (!this.hasMoved && ["KeyW", "KeyA", "KeyS", "KeyD", "Space", "ShiftLeft"].includes(event.code)) { this.hasMoved = true; this.onFirstMovement(); } }); addEventListener("keyup", (event) => this.keys.delete(event.code)); addEventListener("resize", () => this.resize()); this.canvas.addEventListener("pointerdown", (event) => { const rect = this.canvas.getBoundingClientRect(); this.pointer.set(((event.clientX - rect.left) / rect.width) * 2 - 1, -((event.clientY - rect.top) / rect.height) * 2 + 1); this.raycaster.setFromCamera(this.pointer, this.camera); const hits = this.raycaster.intersectObjects(this.planets, true); if (hits[0]) { let object = hits[0].object; while (object.parent && !this.planets.includes(object)) object = object.parent; this.onFocus(object.userData.project); } }); }
  resize() { const { clientWidth: width, clientHeight: height } = this.canvas; if (!width || !height) return; this.camera.aspect = width / height; this.camera.updateProjectionMatrix(); this.renderer.setSize(width, height, false); }
  updateFlight(delta) { const forward = new THREE.Vector3(0, 0, -1).applyQuaternion(this.ship.quaternion); const acceleration = (this.keys.has("KeyW") ? 22 : 0) - (this.keys.has("KeyS") ? 15 : 0); this.ship.userData.velocity.addScaledVector(forward, acceleration * delta); if (this.keys.has("KeyA")) this.ship.rotation.y += 1.45 * delta; if (this.keys.has("KeyD")) this.ship.rotation.y -= 1.45 * delta; if (this.keys.has("Space")) this.ship.userData.velocity.y += 13 * delta; if (this.keys.has("ShiftLeft")) this.ship.userData.velocity.y -= 13 * delta; this.ship.userData.velocity.multiplyScalar(Math.pow(.18, delta)); this.ship.userData.velocity.clampLength(0, 30); this.ship.position.addScaledVector(this.ship.userData.velocity, delta); }
  frame = () => { if (!this.running) return; const delta = Math.min(this.clock.getDelta(), .05); this.updateFlight(delta); const desired = this.ship.position.clone().add(new THREE.Vector3(0, 4.3, 12).applyQuaternion(this.ship.quaternion)); this.camera.position.lerp(desired, 1 - Math.pow(.0004, delta)); this.camera.lookAt(this.ship.position.clone().add(new THREE.Vector3(0, .25, -8).applyQuaternion(this.ship.quaternion))); this.planets.forEach((planet) => { planet.rotation.y += planet.userData.spin; const d = planet.position.distanceTo(this.ship.position); const target = d < 14 ? 1.11 : 1; planet.scale.lerp(new THREE.Vector3(target, target, target), .07); }); this.renderer.render(this.scene, this.camera); requestAnimationFrame(this.frame); };
  start() { if (!this.running) { this.running = true; this.clock.start(); this.frame(); } } stop() { this.running = false; } dispose() { this.stop(); this.renderer.dispose(); }
}
