import { createHash, randomBytes, randomUUID, scryptSync, timingSafeEqual } from "node:crypto";

const SESSION_DAYS = 30;
const isoNow = () => new Date().toISOString();
const tokenHash = (value) => createHash("sha256").update(value).digest("hex");
const passwordHash = (value) => { const salt = randomBytes(16).toString("hex"); return `${salt}:${scryptSync(value, salt, 64).toString("hex")}`; };
const passwordMatches = (value, stored) => { if (!stored) return false; const [salt, hash] = stored.split(":"); const actual = scryptSync(value, salt, 64); return timingSafeEqual(actual, Buffer.from(hash, "hex")); };
const slug = (value) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 64);

export class ApiError extends Error { constructor(status, message) { super(message); this.status = status; } }
export function parseCookies(header = "") { return Object.fromEntries(header.split(";").map((part) => part.trim().split("=")).filter(([key, value]) => key && value).map(([key, value]) => [key, decodeURIComponent(value)])); }
export function sessionUser(db, cookieHeader) {
  const token = parseCookies(cookieHeader).orbitfolio_session; if (!token) return null;
  return db.prepare("SELECT users.id, users.name, users.email, users.bio, users.created_at FROM sessions JOIN users ON users.id = sessions.user_id WHERE sessions.token_hash = ? AND sessions.expires_at > ?").get(tokenHash(token), isoNow()) ?? null;
}
export function requireUser(user) { if (!user) throw new ApiError(401, "Entre para continuar."); return user; }
export function publicUser(db, user, viewerId = null) {
  if (!user) return null;
  return { id:user.id, name:user.name, bio:user.bio, projects:db.prepare("SELECT COUNT(*) AS count FROM projects WHERE owner_id = ?").get(user.id).count, followers:db.prepare("SELECT COUNT(*) AS count FROM follows WHERE followed_id = ?").get(user.id).count, following:viewerId ? !!db.prepare("SELECT 1 FROM follows WHERE follower_id = ? AND followed_id = ?").get(viewerId, user.id) : false };
}
export function publicProject(db, project, viewerId = null) {
  if (!project) return null;
  const owner = db.prepare("SELECT * FROM users WHERE id = ?").get(project.owner_id);
  return { id:project.id, name:project.name, description:project.description, languages:JSON.parse(project.languages_json), githubUrl:project.github_url, demoUrl:project.demo_url, views:project.views, rating:project.rating, updatedAt:project.updated_at, createdAt:project.created_at, likes:db.prepare("SELECT COUNT(*) AS count FROM project_likes WHERE project_id = ?").get(project.id).count, owner:publicUser(db, owner, viewerId), liked:viewerId ? !!db.prepare("SELECT 1 FROM project_likes WHERE user_id = ? AND project_id = ?").get(viewerId, project.id) : false, favorited:viewerId ? !!db.prepare("SELECT 1 FROM favorites WHERE user_id = ? AND project_id = ?").get(viewerId, project.id) : false };
}
export function createSession(db, userId) { const token = randomBytes(32).toString("base64url"); const expiresAt = new Date(Date.now() + SESSION_DAYS * 86400000).toISOString(); db.prepare("INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, ?)").run(tokenHash(token), userId, expiresAt); return { token, expiresAt }; }
export function sessionCookie(token, expiresAt) { return `orbitfolio_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Expires=${new Date(expiresAt).toUTCString()}`; }
export function clearSession(db, header) { const token=parseCookies(header).orbitfolio_session; if(token) db.prepare("DELETE FROM sessions WHERE token_hash = ?").run(tokenHash(token)); return "orbitfolio_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0"; }
export function register(db, input) { const name=String(input.name ?? "").trim(), email=String(input.email ?? "").trim().toLowerCase(), password=String(input.password ?? ""); if(name.length<2 || name.length>80) throw new ApiError(422,"Informe um nome entre 2 e 80 caracteres."); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new ApiError(422,"Informe um e-mail válido."); if(password.length<8) throw new ApiError(422,"A senha deve ter ao menos 8 caracteres."); if(db.prepare("SELECT 1 FROM users WHERE email = ?").get(email)) throw new ApiError(409,"Este e-mail já possui uma conta."); const user={id:randomUUID(),name,email,bio:"Explorador(a) da comunidade Orbitfolio."}; db.prepare("INSERT INTO users (id, name, email, password_hash, bio) VALUES (?, ?, ?, ?, ?)").run(user.id,user.name,user.email,passwordHash(password),user.bio); return user; }
export function login(db, input) { const email=String(input.email ?? "").trim().toLowerCase(), password=String(input.password ?? ""); const user=db.prepare("SELECT * FROM users WHERE email = ?").get(email); if(!user || !passwordMatches(password,user.password_hash)) throw new ApiError(401,"E-mail ou senha inválidos."); return user; }
export function createProject(db, user, input) { const name=String(input.name ?? "").trim(), description=String(input.description ?? "").trim(); if(name.length<2 || name.length>100) throw new ApiError(422,"Informe um nome entre 2 e 100 caracteres."); if(description.length<10 || description.length>500) throw new ApiError(422,"A descrição deve ter entre 10 e 500 caracteres."); const rawLanguages=input.languages && typeof input.languages === "object" ? input.languages : {}; const languages=Object.fromEntries(Object.entries(rawLanguages).filter(([key,value]) => typeof key === "string" && Number.isFinite(Number(value)) && Number(value)>0).slice(0,8)); if(!Object.keys(languages).length) throw new ApiError(422,"Informe ao menos uma linguagem e seu percentual."); const validUrl=(value) => !value || /^https?:\/\//i.test(value); if(!validUrl(input.githubUrl) || !validUrl(input.demoUrl)) throw new ApiError(422,"Use URLs http(s) válidas."); let id=slug(name); if(!id) throw new ApiError(422,"Nome de projeto inválido."); if(db.prepare("SELECT 1 FROM projects WHERE id = ?").get(id)) id=`${id}-${randomUUID().slice(0,6)}`; const now=isoNow(); db.prepare("INSERT INTO projects (id, owner_id, name, description, languages_json, github_url, demo_url, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(id,user.id,name,description,JSON.stringify(languages),String(input.githubUrl ?? ""),String(input.demoUrl ?? ""),now,now); db.prepare("INSERT INTO commits (id, project_id, message, author_name, committed_at) VALUES (?, ?, ?, ?, ?)").run(randomUUID(),id,"Projeto publicado no Orbitfolio",user.name,now); return db.prepare("SELECT * FROM projects WHERE id = ?").get(id); }
export function setRelation(db, table, fields, values, active) { const where=fields.map((field)=>`${field} = ?`).join(" AND "); const existing=db.prepare(`SELECT 1 FROM ${table} WHERE ${where}`).get(...values); if(active && !existing) db.prepare(`INSERT INTO ${table} (${fields.join(", ")}) VALUES (${fields.map(()=>"?").join(", ")})`).run(...values); if(!active && existing) db.prepare(`DELETE FROM ${table} WHERE ${where}`).run(...values); }
export function rankingProjects(db, viewerId, period) { const days={week:7,month:30,all:null}[period] ?? null; const params=days?[new Date(Date.now()-days*86400000).toISOString()]:[]; const clause=days?"WHERE project_likes.created_at >= ?":""; const rows=db.prepare(`SELECT projects.*, COUNT(project_likes.user_id) AS period_likes FROM projects LEFT JOIN project_likes ON project_likes.project_id = projects.id ${clause} GROUP BY projects.id ORDER BY period_likes DESC, projects.views DESC, projects.updated_at DESC`).all(...params); return rows.map((row)=>publicProject(db,row,viewerId)); }
